Running SLURM prolog script on pink60
===============================================================================
Job started on Sat Aug  4 18:37:31 BST 2018
Job ID          : 123672
Job name        : saliency-batch
WorkDir         : /mainfs/lyceum/grm1g17/lasagne4bio/test_saliency
Partition       : lyceum
Num hosts       : 1
Num cores       : 14
Num of tasks    : 14
Hosts allocated : pink60
Job Output Follows ...
===============================================================================
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:82:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
==============================================================================
Running epilogue script on pink60.

Submit time  : 2018-08-04T18:37:31
Start time   : 2018-08-04T18:37:31
End time     : 2018-08-04T18:46:05
Elapsed time : 00:08:34 (Timelimit=05:40:00)

Job ID: 123672
Array Job ID: 123671_1
Cluster: i5
User/Group: grm1g17/fp
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 14
CPU Utilized: 00:02:31
**** Please note that the CPU efficency of your job is less than 50% ****
**** Ask the HPC team for advice -- if you need it
**** CPU Efficiency: 2.10% of 01:59:56 core-walltime

Memory Utilized: 2.24 GB

