Running SLURM prolog script on pink58
===============================================================================
Job started on Sat Aug  4 18:43:04 BST 2018
Job ID          : 123671
Job name        : saliency-batch
WorkDir         : /mainfs/lyceum/grm1g17/lasagne4bio/test_saliency
Partition       : lyceum
Num hosts       : 1
Num cores       : 14
Num of tasks    : 14
Hosts allocated : pink58
Job Output Follows ...
===============================================================================
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
INFO (theano.gof.compilelock): Waiting for existing lock by process '26123' (I am process '39548')
INFO (theano.gof.compilelock): To manually release the lock, delete /mainfs/lyceum/grm1g17/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-redhat-7.4-Maipo-x86_64-3.5.5-64/lock_dir
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Train path is downloaded ...
Loading train data ...
Loading splits ...
Traceback (most recent call last):
  File "saliency.py", line 295, in <module>
    main_saliencies_jurtz()
  File "saliency.py", line 241, in main_saliencies_jurtz
    idx = range(args.batch * batch_size, (batch + 1) * batch_size)
NameError: name 'batch' is not defined
